NewsPortal/NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
   path('admin/', admin.site.urls),
   path('pages/', include('django.contrib.flatpages.urls')),
   # Делаем так, чтобы все адреса из нашего приложения (simpleapp/urls.py)
   # подключались к главному приложению с префиксом products/.
   path('', include('news.urls')),
   path('accounts/', include("allauth.urls")),
]

NewsPortal/news/urls.py
from django.urls import path
# Импортируем созданные нами представления
from .views import *
from django.views.decorators.cache import cache_page

urlpatterns = [
   # path — означает путь.
   # В данном случае путь ко всем товарам у нас останется пустым.
   # Т.к. наше объявленное представление является классом,
   # а Django ожидает функцию, нам надо представить этот класс в виде view.
   # Для этого вызываем метод as_view.
   path('posts/',cache_page(60)(PostsList.as_view()), name='posts_list'),
   # pk — это первичный ключ товара, который будет выводиться у нас в шаблон
   # int — указывает на то, что принимаются только целочисленные значения
   path('post/<int:pk>/', cache_page(60*5)(PostDetail.as_view()), name='posts_detail'),
   path('news/create/', NewsCreate.as_view()),
   path('articles/create/', ArticleCreate.as_view()),
   path('news/<int:pk>/edit/', NewsEdit.as_view(), name='post_edit'),
   path('articles/<int:pk>/edit/', ArticleEdit.as_view(), name='post_edit'),
   path('news/<int:pk>/delete/', NewsDelete.as_view()),
   path('articles/<int:pk>/delete/', ArticleDelete.as_view()),
   path('subscriptions/', subscriptions, name='subscriptions'),

]

NewsPortal/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import pgettext_lazy  # импортируем «ленивый» геттекст с подсказкой



# Create your models here.
class Author(models.Model):
     author = models.OneToOneField(User, on_delete=models.CASCADE)
     rating = models.IntegerField(default=0)

     def update_rating(self):
         post_ratings = self.post_set.aggregate(total=models.Sum('rating'))
         post_rating_total = post_ratings * 3

         # Суммарный рейтинг всех комментариев автора
         author_comments_ratings = self.user.comment_set.aggregate(total=models.Sum('rating'))

         # Суммарный рейтинг всех комментариев к статьям автора
         post_comments_ratings = Comment.objects.filter(post__author=self).aggregate(total=models.Sum('rating'))

         # Общий рейтинг автора
         self.rating = post_rating_total + author_comments_ratings + post_comments_ratings
         self.save()

     def __str__(self):
         return self.author.username  # Возвращаем имя пользователя





class Category(models.Model):
    name = models.CharField(max_length=100,
                            help_text=_('category name'))  # добавим переводящийся текст подсказку к полю

    def __str__(self):
        return self.category


class Post(models.Model):
    news = "NE"
    article = "AR"
    POSITION = [(news, "Новость"),(article, "Статья")]
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    position =models.CharField(max_length=2, choices=POSITION)
    time_in = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, through="PostCategory")
    heading = models.TextField()
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[:124] + "..."

    def __str__(self):
        formatted_time = self.time_in.strftime('%d %B %Y')
        return f'{self.heading}: {formatted_time}: {self.text}'

    def get_absolute_url(self):
        return reverse('posts_detail', args=[str(self.id)])



class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    time_in = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)


    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subscriptions')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='subscriptions')


class MyModel(models.Model):
    name = models.CharField(max_length=100)
    kind = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='kinds',
        verbose_name=pgettext_lazy('help text for MyModel model', 'This is the help text'),
    )

NewsPortal/templates/article_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.heding }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPortal/templates/article_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPortal/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
  {% for post in posts%}
    <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a> </li>
  {% endfor %}
</ul>
</body>
</html>

NewsPortal/templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.heading }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPortal/templates/news_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPortal/templates/post.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

<!-- Название у нас будет Product -->
{% block title %}
Post
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ post }}</h1>
{% endblock content %}

NewsPortal/templates/posts.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}
   <h1>Все новости</h1>
    <h3>{{ posts|length }}</h3>


   <hr>
   {% if posts %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата публикации</td>
               <td>Текст</td>

               {# Условие получается составным. #}
                {% if perms.news.change_post %}
                <td>Действия</td>
                {% endif %}
           </tr>

           {% for post in posts %}
           <tr>
               <td>{{ post.heading|censor }}</td>
               <td>{{ time_now|date:'M d Y' }}</td>
               <td>{{ post.text|truncatewords:20|censor }}</td>


               <td>
                    {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
                    {% if perms.news.change_post %}
                    <a href="{% url 'post_edit' post.id %}">Изменить</a>
                    {% endif %}


                </td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}

       {# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

NewsPortal/templates/search.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}
   <h1>Все товары</h1>

   {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>

   <hr>
   {% if posts %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата публикации</td>
               <td>Текст</td>
           </tr>

           {% for post in posts %}
           <tr>
               <td>{{ post.heading|censor }}</td>
               <td>{{ time_now|date:'M d Y' }}</td>
               <td>{{ post.text|truncatewords:20|censor }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}



{% endblock content %}

NewsPortal/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscription
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.category }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}